//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesJapanese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesJapanese() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Students.Resources.ResourcesJapanese", typeof(ResourcesJapanese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 著者.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受講可能な科目.
        /// </summary>
        internal static string AvailableSubjects {
            get {
                return ResourceManager.GetString("AvailableSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトル.
        /// </summary>
        internal static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容量.
        /// </summary>
        internal static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選ばれた被験者.
        /// </summary>
        internal static string ChosenSubjects {
            get {
                return ResourceManager.GetString("ChosenSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教室.
        /// </summary>
        internal static string Classrooms {
            get {
                return ResourceManager.GetString("Classrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成する.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クレジット.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消去.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  これを削除してもよろしいですか?.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 説明.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 床.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 家.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リストに戻る.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主題の索引.
        /// </summary>
        internal static string IndexSubjects {
            get {
                return ResourceManager.GetString("IndexSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to について学ぶ.
        /// </summary>
        internal static string LearnAbout {
            get {
                return ResourceManager.GetString("LearnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 講師.
        /// </summary>
        internal static string Lecturer {
            get {
                return ResourceManager.GetString("Lecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 講師.
        /// </summary>
        internal static string Lecturers {
            get {
                return ResourceManager.GetString("Lecturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET Core を使用した Web アプリの構築.
        /// </summary>
        internal static string LinkASP {
            get {
                return ResourceManager.GetString("LinkASP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選考科目.
        /// </summary>
        internal static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  名前.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前.
        /// </summary>
        internal static string NameOfSubject {
            get {
                return ResourceManager.GetString("NameOfSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 番号.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オペレーション.
        /// </summary>
        internal static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プライバシーポリシー.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  学生.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科目.
        /// </summary>
        internal static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生のインデックス.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このページを使用して、サイトのプライバシー ポリシーを詳しく説明します。.
        /// </summary>
        internal static string UsePolicy {
            get {
                return ResourceManager.GetString("UsePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いらっしゃいませ.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
